version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  frontend:
    build: ./frontend
    depends_on:
      - web
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app

  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/time_manager
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    command: >
      bash -c "mix ecto.create && mix ecto.migrate && mix phx.server"

volumes:
  postgres_data: